name: Migrate Garmin CN to Garmin Global

 on:
   workflow_dispatch:
env:
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
  GARMIN_MIGRATE_NUM: ${{ secrets.GARMIN_MIGRATE_NUM }}
  GARMIN_MIGRATE_START: ${{ secrets.GARMIN_MIGRATE_START }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Migrate Garmin CN to Garmin Global
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn migrate_garmin_cn_to_global
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Garmin Session
